### ISSUE TITLE
Add Dropbox Link to Markdown File to Database

### ISSUE THREAD

**Issue by atandrewlee** [atandrewlee/CRM_Server#30]
# Dropbox API
"Look into Sharing Section"
- get_file_metadata

# Tasks
- [ ] When file is created, get the return resulting value of the file -> activate sharing -> get the sharing link from the metadata -> add it to the database -> have it update the YAML
    - [ ] Setup return value of the dropbox create file
    - [ ] Call Dropbox to setup sharing
    - [ ] Get the sharing link from the return value of previous step
    - [ ] Add the link to the database

- [ ] Update the YAML update (Database -> Markdown) to add this link
